### ISSUE TITLE
Function callbacks panic inside of `JSONStringify`

### ISSUE THREAD

**Issue by colinking** [rogchap/v8go#186]
We're running into a crash with v8go when using `.JSONStringify()`. I put together a minimal example ([full code here](https://github.com/colinking/v8-experiments/blob/main/proxy-crash/main.go)):

<details>

```go
package main

import (
	"fmt"

	// This example uses our fork for darwin_arm64 support, but the issue
	// should surface using the upstream master, too:
	// v8 "rogchap.com/v8go"
	v8 "github.com/airplanedev/v8go"
)

var code = `
	new Proxy({}, {
		get: function () {
			foobar()
			return "hello!"
		},
	})
`

func main() {
	iso := v8.NewIsolate()
	defer iso.Dispose()

	global := v8.NewObjectTemplate(iso)
	err := global.Set("foobar", v8.NewFunctionTemplate(iso, func(info *v8.FunctionCallbackInfo) *v8.Value {
		v8v, _ := v8.NewValue(iso, "callback")
		return v8v
	}))
	if err != nil {
		panic(fmt.Errorf("setting global: %w", err))
	}

	v8ctx := v8.NewContext(iso, global)
	defer v8ctx.Close()

	v8v, err := v8ctx.RunScript(code, "main.js")
	if err != nil {
		panic(fmt.Errorf("running script: %w", err))
	}

	s, err := v8.JSONStringify(nil, v8v)
	if err != nil {
		panic(fmt.Errorf("stringifying value: %w", err))
	}
	fmt.Println(s)
}
```

</details>

If you run it with `go run ./main.go`, it'll produce the following crash log:

<details>

```
❯ go run ./main.go

#
# Fatal error in v8::Isolate::Dispose()
# Disposing the isolate that is entered by a thread.
#

SIGTRAP: trace trap
PC=0x104a81fe8 m=0 sigcode=0

goroutine 0 [idle]:
runtime: unknown pc 0x104a81fe8
stack: frame={sp:0x16b4333d0, fp:0x0} stack=[0x16b3b43e8,0x16b433460)
0x000000016b4332d0:  0x0001000200030003  0x0000000000000000
0x000000016b4332e0:  0x0000000000000000  0x0000000000000000
0x000000016b4332f0:  0x0000000000000000  0x0000000000000000
0x000000016b433300:  0x0000000000000000  0x0000000000000000
0x000000016b433310:  0x0000000000000000  0x0000000000000000
0x000000016b433320:  0x0000000000000000  0x0000000000000000
0x000000016b433330:  0x0000000000000000  0x0000000000000000
0x000000016b433340:  0x0000000000000000  0x0000000000000000
0x000000016b433350:  0x0000000000000016  0x00000001fb03aab0
0x000000016b433360:  0x000000016b433380  0xe26a80018faed934
0x000000016b433370:  0x0000000105555519  0x0000000000000063
0x000000016b433380:  0x000000016b4333b0  0xbd2300018faf5918
0x000000016b433390:  0x0000000000000002  0x0000315a00000000
0x000000016b4333a0:  0x0000000000000028  0x0000315a0000c782
0x000000016b4333b0:  0x000000016b4333d0  0x970e800104a825f4
0x000000016b4333c0:  0x0000000000000002  0x000000016b4333e0
0x000000016b4333d0: <0x000000016b433400  0x0000000104a91850
0x000000016b4333e0:  0x000000010555886a  0x0000000105558881
0x000000016b4333f0:  0x0000000000000028  0x0000000000000000
0x000000016b433400:  0x0000000000000000  0x0000000104a302fc <runtime.asmcgocall+0x000000000000007c>
0x000000016b433410:  0x00000140000001a0  0x0000000000000770
0x000000016b433420:  0x0000000104a2dfd0 <runtime.mstart+0x0000000000000010>  0x00000001056e8280
0x000000016b433430:  0x0000000104a2df94 <runtime.rt0_go+0x00000000000000f4>  0x000000016b433478
0x000000016b433440:  0x00000001056e8280  0x000000016b433478
0x000000016b433450:  0x0000000104a2df9c <runtime.rt0_go+0x00000000000000fc>  0x0000000000000000
runtime: unknown pc 0x104a81fe8
stack: frame={sp:0x16b4333d0, fp:0x0} stack=[0x16b3b43e8,0x16b433460)
0x000000016b4332d0:  0x0001000200030003  0x0000000000000000
0x000000016b4332e0:  0x0000000000000000  0x0000000000000000
0x000000016b4332f0:  0x0000000000000000  0x0000000000000000
0x000000016b433300:  0x0000000000000000  0x0000000000000000
0x000000016b433310:  0x0000000000000000  0x0000000000000000
0x000000016b433320:  0x0000000000000000  0x0000000000000000
0x000000016b433330:  0x0000000000000000  0x0000000000000000
0x000000016b433340:  0x0000000000000000  0x0000000000000000
0x000000016b433350:  0x0000000000000016  0x00000001fb03aab0
0x000000016b433360:  0x000000016b433380  0xe26a80018faed934
0x000000016b433370:  0x0000000105555519  0x0000000000000063
0x000000016b433380:  0x000000016b4333b0  0xbd2300018faf5918
0x000000016b433390:  0x0000000000000002  0x0000315a00000000
0x000000016b4333a0:  0x0000000000000028  0x0000315a0000c782
0x000000016b4333b0:  0x000000016b4333d0  0x970e800104a825f4
0x000000016b4333c0:  0x0000000000000002  0x000000016b4333e0
0x000000016b4333d0: <0x000000016b433400  0x0000000104a91850
0x000000016b4333e0:  0x000000010555886a  0x0000000105558881
0x000000016b4333f0:  0x0000000000000028  0x0000000000000000
0x000000016b433400:  0x0000000000000000  0x0000000104a302fc <runtime.asmcgocall+0x000000000000007c>
0x000000016b433410:  0x00000140000001a0  0x0000000000000770
0x000000016b433420:  0x0000000104a2dfd0 <runtime.mstart+0x0000000000000010>  0x00000001056e8280
0x000000016b433430:  0x0000000104a2df94 <runtime.rt0_go+0x00000000000000f4>  0x000000016b433478
0x000000016b433440:  0x00000001056e8280  0x000000016b433478
0x000000016b433450:  0x0000000104a2df9c <runtime.rt0_go+0x00000000000000fc>  0x0000000000000000

goroutine 1 [syscall]:
runtime.cgocall(0x104a69010, 0x14000051928)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:156 +0x50 fp=0x140000518e0 sp=0x140000518a0 pc=0x1049d2930
github.com/airplanedev/v8go._Cfunc_IsolateDispose(0x315a00000000)
	_cgo_gotypes.go:341 +0x40 fp=0x14000051920 sp=0x140000518e0 pc=0x104a63430
github.com/airplanedev/v8go.(*Isolate).Dispose.func1(0x14000130000)
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/isolate.go:102 +0x58 fp=0x14000051960 sp=0x14000051920 pc=0x104a65be8
github.com/airplanedev/v8go.(*Isolate).Dispose(0x14000130000)
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/isolate.go:102 +0x30 fp=0x14000051980 sp=0x14000051960 pc=0x104a65b60
runtime.call16(0x0, 0x105655a78, 0x14000100098, 0x8, 0x8, 0x8, 0x140000519d8)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:414 +0x74 fp=0x140000519a0 sp=0x14000051980 pc=0x104a2e4c4
runtime.reflectcallSave(0x14000051b00, 0x105655a78, 0x14000100098, 0x8)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/panic.go:927 +0xa8 fp=0x140000519e0 sp=0x140000519a0 pc=0x104a01d68
runtime.runOpenDeferFrame(0x140000001a0, 0x14000100050)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/panic.go:891 +0x28c fp=0x14000051a60 sp=0x140000519e0 pc=0x104a0173c
panic({0x105645560, 0x1056d39e0})
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/panic.go:1038 +0x21c fp=0x14000051b40 sp=0x14000051a60 pc=0x104a01fcc
runtime.panicmem()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/panic.go:221 +0x58 fp=0x14000051b60 sp=0x14000051b40 pc=0x1049fff18
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/signal_unix.go:735 +0x1fc fp=0x14000051ba0 sp=0x14000051b60 pc=0x104a1887c
github.com/airplanedev/v8go.goContext(...)
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/context.go:167
_cgoexp_3044003ff71f_goContext(0x16b4328a0)
	_cgo_gotypes.go:1823 +0x30 fp=0x14000051be0 sp=0x14000051bb0 pc=0x104a684a0
runtime.cgocallbackg1(0x104a68470, 0x16b4328a0, 0x0)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:306 +0x1f4 fp=0x14000051cb0 sp=0x14000051be0 pc=0x1049d2d24
runtime.cgocallbackg(0x104a68470, 0x16b4328a0, 0x0)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:232 +0xe0 fp=0x14000051d30 sp=0x14000051cb0 pc=0x1049d2aa0
runtime.cgocallback(0x14000051da8, 0x104a634c4, 0x104a6919c)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1055 +0x98 fp=0x14000051d60 sp=0x14000051d30 pc=0x104a303f8
runtime.systemstack_switch()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:187 +0x8 fp=0x14000051d70 sp=0x14000051d60 pc=0x104a2e058
runtime.cgocall(0x104a6919c, 0x14000051df8)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:166 +0x70 fp=0x14000051db0 sp=0x14000051d70 pc=0x1049d2950
github.com/airplanedev/v8go._Cfunc_JSONStringify(0x0, 0x157e22b40)
	_cgo_gotypes.go:420 +0x44 fp=0x14000051df0 sp=0x14000051db0 pc=0x104a634c4
github.com/airplanedev/v8go.JSONStringify.func1(0x0, {0x105656740, 0x14000112320})
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/json.go:39 +0xa0 fp=0x14000051e40 sp=0x14000051df0 pc=0x104a660f0
github.com/airplanedev/v8go.JSONStringify(0x0, {0x105656740, 0x14000112320})
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/json.go:39 +0x78 fp=0x14000051e90 sp=0x14000051e40 pc=0x104a65ea8
main.main()
	/Users/colin/dev/colinking/v8-experiments/proxy-crash/main.go:54 +0x1f8 fp=0x14000051f70 sp=0x14000051e90 pc=0x104a68a28
runtime.main()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/proc.go:255 +0x284 fp=0x14000051fd0 sp=0x14000051f70 pc=0x104a04de4
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1133 +0x4 fp=0x14000051fd0 sp=0x14000051fd0 pc=0x104a304d4

r0      0x63
r1      0x0
r2      0x120a8
r3      0x16b432eeb
r4      0x16b432a40
r5      0x16b4333e0
r6      0xa
r7      0x1
r8      0x1
r9      0x1fb03c8d0
r10     0x2
r11     0xfffffffd
r12     0x10000000000
r13     0x0
r14     0x0
r15     0x0
r16     0x18fba97d8
r17     0x1fe665650
r18     0x0
r19     0x315a0000c782
r20     0x28
r21     0x315a00000000
r22     0x2
r23     0x1
r24     0x1056dad48
r25     0x315a00000090
r26     0x105655a78
r27     0x818
r28     0x1056e8280
r29     0x16b4333d0
lr      0x104a91850
sp      0x16b4333d0
pc      0x104a81fe8
fault   0x104a81fe8
exit status 2
```

</details>

The `v8::Isolate::Dispose()` warning is a red herring, since it's producing a panic before the `Dispose()` call fails:

<details>

```
...
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/signal_unix.go:735 +0x1fc fp=0x14000051ba0 sp=0x14000051b60 pc=0x104a1887c
github.com/airplanedev/v8go.goContext(...)
	/Users/colin/go/pkg/mod/github.com/airplanedev/v8go@v0.6.1-0.20210928213729-875d270618bb/context.go:167
_cgoexp_3044003ff71f_goContext(0x16b4328a0)
	_cgo_gotypes.go:1823 +0x30 fp=0x14000051be0 sp=0x14000051bb0 pc=0x104a684a0
runtime.cgocallbackg1(0x104a68470, 0x16b4328a0, 0x0)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:306 +0x1f4 fp=0x14000051cb0 sp=0x14000051be0 pc=0x1049d2d24
runtime.cgocallbackg(0x104a68470, 0x16b4328a0, 0x0)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:232 +0xe0 fp=0x14000051d30 sp=0x14000051cb0 pc=0x1049d2aa0
runtime.cgocallback(0x14000051da8, 0x104a634c4, 0x104a6919c)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:1055 +0x98 fp=0x14000051d60 sp=0x14000051d30 pc=0x104a303f8
runtime.systemstack_switch()
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/asm_arm64.s:187 +0x8 fp=0x14000051d70 sp=0x14000051d60 pc=0x104a2e058
runtime.cgocall(0x104a6919c, 0x14000051df8)
	/opt/homebrew/Cellar/go/1.17/libexec/src/runtime/cgocall.go:166 +0x70 fp=0x14000051db0 sp=0x14000051d70 pc=0x1049d2950
github.com/airplanedev/v8go._Cfunc_JSONStringify(0x0, 0x157e22b40)
	_cgo_gotypes.go:420 +0x44 fp=0x14000051df0 sp=0x14000051db0 pc=0x104a634c4
...
```

</details>

Capturing that panic yields:

```
runtime error: invalid memory address or nil pointer dereference
```

From the stack trace, I can see the issue stems from the `JSON.stringify` call which at some point calls [`goContext`](https://github.com/airplanedev/v8go/blob/875d270618bb50e48f1c16492a5697a50fd176c8/context.go#L167) -- [presumably here](https://github.com/airplanedev/v8go/blob/875d270618bb50e48f1c16492a5697a50fd176c8/v8go.cc#L285-L291). Since the panic is thrown from Go, I'm guessing `ctx` is nil when it evaluates `ctx.ptr` in `goContext`.

That's about as far as I've gotten so far. Curious if y'all have any advice?

I believe the issue may stem from the stringify call attempting to invoke the injected callback (`foobar`), but that some metadata is not properly available compared to during `RunScript`.

**Comment by colinking** [comment]
Ah, I see what's going on. The context registry is only updated during `RunScript` calls: https://github.com/rogchap/v8go/blob/fd090e9d087ba54d602489d47c821182c6da8250/context.go#L95-L97

Therefore, you can't access function callbacks outside of `RunScript` calls, such as in calls to `JSONStringify`.

As a fix, is it possible to register the context in the registry when the context is first created and then wait to deregister until `context.Close()`? Something like this: https://github.com/rogchap/v8go/pull/187
