### ISSUE TITLE
[bug] segmentation violation panic after garbage collection

### ISSUE THREAD

**Issue by inn0kenty** [rogchap/v8go#81]
Hello!

I investigate random segmentation violation panics. This happens when GC execute value finalizer on disposed isolate. 

Maybe related to #39.

Code to reproduce.

```go
package main

import (
	"fmt"
	"runtime"
	"time"

	"rogchap.com/v8go"
)

func main() {
	iso, _ := v8go.NewIsolate()
	v8ctx, _ := v8go.NewContext(iso)
	val, _ := v8go.NewValue(iso, "some string")

	fmt.Println(val.String())

	v8ctx.Close()
	iso.Dispose()

	runtime.GC() // force garbage collection

	time.Sleep(time.Second)
}
``` 

Stack trace

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4232ee8]

runtime stack:
runtime.throw(0x4c066c4, 0x2a)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/panic.go:1117 +0x72
runtime.sigpanic()
        /usr/local/Cellar/go/1.16/libexec/src/runtime/signal_unix.go:718 +0x2ef

goroutine 5 [syscall]:
runtime.cgocall(0x40adde0, 0xc00004ee90, 0xf)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/cgocall.go:154 +0x5b fp=0xc00004ee60 sp=0xc00004ee28 pc=0x400657b
rogchap.com/v8go._Cfunc_ValueFree(0xcb185e0)
        _cgo_gotypes.go:618 +0x3c fp=0xc00004ee90 sp=0xc00004ee60 pc=0x40aa91c
rogchap.com/v8go.(*Value).finalizer.func1(0xc0000122e0)
        /Users/user/projects/project/vendor/rogchap.com/v8go/value.go:530 +0x55 fp=0xc00004eec8 sp=0xc00004ee90 pc=0x40ad155
rogchap.com/v8go.(*Value).finalizer(0xc0000122e0)
        /Users/user/projects/project/vendor/rogchap.com/v8go/value.go:530 +0xa5 fp=0xc00004ef38 sp=0xc00004eec8 pc=0x40ac4a5
runtime.call16(0x0, 0x4c07d70, 0xc00001a070, 0x1000000010)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:550 +0x3e fp=0xc00004ef58 sp=0xc00004ef38 pc=0x4066afe
runtime.runfinq()
        /usr/local/Cellar/go/1.16/libexec/src/runtime/mfinal.go:222 +0x1f4 fp=0xc00004efe0 sp=0xc00004ef58 pc=0x401aab4
runtime.goexit()
        /usr/local/Cellar/go/1.16/libexec/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00004efe8 sp=0xc00004efe0 pc=0x4068541
created by runtime.createfing
        /usr/local/Cellar/go/1.16/libexec/src/runtime/mfinal.go:156 +0x65

goroutine 1 [sleep]:
time.Sleep(0x3b9aca00)
        /usr/local/Cellar/go/1.16/libexec/src/runtime/time.go:193 +0xd2
main.main()
        /Users/user/projects/project/tst/main.go:23 +0x146
```

**Comment by rogchap** [comment]
Thanks for reporting @inn0kenty 
Will investigate.

**Comment by robfig** [comment]
I ran into this too. Thanks

**Comment by sander-m** [comment]
👋 Would it be possible to create a new release for this (critical) bug? I think I'm running into this issue with `0.5.1`.
